### ISSUE TITLE
Collected patches for consideration in next release.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjjf/advanced-shell-history#23]
```
I've come up with a collection of patches that resolve a number of the issues 
reported against this project. I'm creating this report as a catch-all to 
collect these in one place.

At this point I'm starting to think that moving this project to github would be 
a good idea, though without being able to modify these pages it would be hard 
for existing users to get from here to there.

Simon
```

Original issue reported on code.google.com by `sjjfow...@gmail.com` on 3 Jul 2015 at 12:32

Attachments:
* [ash-sjjf-collected-fixes-20150703.patch](https://storage.googleapis.com/google-code-attachments/advanced-shell-history/issue-23/comment-0/ash-sjjf-collected-fixes-20150703.patch)
* [ash-sjjf-proposed-dont-pretend-we-know-where-_ash-log-is-20150703.patch](https://storage.googleapis.com/google-code-attachments/advanced-shell-history/issue-23/comment-0/ash-sjjf-proposed-dont-pretend-we-know-where-_ash-log-is-20150703.patch)
* [ash-sjjf-proposed-interactive-shell-fix-20150703.patch](https://storage.googleapis.com/google-code-attachments/advanced-shell-history/issue-23/comment-0/ash-sjjf-proposed-interactive-shell-fix-20150703.patch)
* [ash-sjjf-proposed-source-should-not-exit-20150703.patch](https://storage.googleapis.com/google-code-attachments/advanced-shell-history/issue-23/comment-0/ash-sjjf-proposed-source-should-not-exit-20150703.patch)

**Comment by sjjf** [comment]
Integrated in the github version.
